In [83]:
import numpy as np
from QMCP.functions import vmc
import matplotlib.pyplot as plt


def function(alpha, r1, r2, r):
    func = np.exp(-2*r1 - 2*r2 + r/(2*(1+alpha*r)))
    return(func)

def six_d_metropolis(N, n_walkers):
    
    x = np.zeros((2,N,n_walkers))
    displacement = np.random.rand(2,dim,n_walkers)
    x[:,0,:] = np.linalg.norm(displacement, axis = 1)
    
    for i in range(N):
        trial_displacement = displacement + (0.2*(np.random.rand(2,dim,n_walkers)*4-2))
        x_trial_0 = np.linalg.norm(trial_displacement[0,:,:], axis=1)
        x_trial_1 = np.linalg.norm(trial_displacement[1,:,:], axis=1)
        x_trial_difference = abs(x_trial_0 - x_trial_1)
        r = function(alpha, x_trial_0, x_trial_1, x_trial_difference)/function(alpha, x[0,i-1,:], x[1,i-1,:], abs(x[0,i-1,:]-x[1,i-1,:]))
        eta = np.random.uniform(0,1,size = n_walkers)
        x[0,i,:] = np.where(r >= 1, x_trial_0, (np.where(eta < r, x_trial_0, x[0,i-1,:]))) 
        x[1,i,:] = np.where(r >= 1, x_trial_1, (np.where(eta < r, x_trial_1, x[0,i-1,:]))) 
        displacement = np.where(r>=1, trial_displacement,(np.where(eta < r, trial_displacement, displacement)))
        
    x0 = np.reshape(x[0,1000:,:], n_walkers*N - (n_walkers * 1000))
    x1 = np.reshape(x[1,1000:,:], n_walkers*N - (n_walkers * 1000))
    
    x0, x1 = np.where(abs(x)<0.005, 0.1 , x)
    return(x0, x1)

walker1, walker2 = six_d_metropolis(1000,3)


(1000, 3)


In [75]:
x = np.random.rand(2,2,2)
print(x)
print(10)
print(x[:,1:,:])
x = np.reshape(x, 8)
print(x)

[[[ 0.72010346  0.05385149]
  [ 0.15095108  0.7168054 ]]

 [[ 0.64139514  0.76488577]
  [ 0.61011162  0.09903975]]]
10
[[[ 0.15095108  0.7168054 ]]

 [[ 0.61011162  0.09903975]]]
[ 0.72010346  0.05385149  0.15095108  0.7168054   0.64139514  0.76488577
  0.61011162  0.09903975]


[]
